# Generated by Django 6.1 on 2026-08-07 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('text', 'متن'), ('image', 'عکس'), ('video', 'ویدئو')], max_length=10, verbose_name='نوع پست')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='عنوان')),
                ('content', models.TextField(blank=True, verbose_name='متن پست')),
                ('location_type', models.CharField(blank=True, choices=[('شهر', 'شهر'), ('روستا', 'روستا')], max_length=10, null=True, verbose_name='نوع مکان (فقط بنگاه)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('likes_count', models.IntegerField(default=0, verbose_name='تعداد لایک')),
                ('comments_count', models.IntegerField(default=0, verbose_name='تعداد کامنت')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category', verbose_name='دسته\u200cبندی')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پست',
                'verbose_name_plural': 'پست\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='posts/%Y/%m/%d/', verbose_name='فایل')),
                ('media_type', models.CharField(choices=[('image', 'تصویر'), ('video', 'ویدئو')], max_length=10, verbose_name='نوع رسانه')),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='posts.post', verbose_name='پست')),
            ],
            options={
                'verbose_name': 'رسانه',
                'verbose_name_plural': 'رسانه\u200cها',
                'ordering': ['order'],
            },
        ),
    ]
